url: "https://dev.adipurnm.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
donate_url: "https://nihbuatjajan.com/adipurnm"
title: "adipurnm" # the name of your site, e.g. ACME Corp.
locale: id_ID
permalink: /:title
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/adi-og.jpg

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
